### ISSUE TITLE
Decisions regarding the use of computer vision on the robot need to be made

### ISSUE THREAD

**Issue by Omenien** [SarahHeinzHouseFRC/RecycleRush#1]
The current date set for this is January 17th, 2015. I realize that this is very little time but in order to fully flesh out the necessary features, we'll need to have our mind made up fairly soon. If possible, update this Issue with information pertinent to the decision such as testing results.

**Comment by LucasSwitz** [comment]
Request for reopen as the feature is not complete. I have just started testing a new CV solution that launches potatoes in a ~110 degree arc from an air cannon and captures the sound feedback to detect features in the environment. 

Call it: potadar.

**Comment by eddie-on-gh** [comment]
@LucasSwitz should I try to secure VC funding?
